<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ticky-PC" name="BackEndTesting.MessageEntityTest" tests="11" failures="8" timestamp="8 May 2015 18:20:01 GMT" time="0.778" errors="0">
  <testcase name="retrieveMessages" time="0.004" classname="BackEndTesting.MessageEntityTest">
    <failure type="com.google.apphosting.api.ApiProxy$CallNotFoundException" message="The API package &#039;datastore_v3&#039; or call &#039;RunQuery()&#039; was not found.">
      <![CDATA[com.google.apphosting.api.ApiProxy$CallNotFoundException: The API package 'datastore_v3' or call 'RunQuery()' was not found.
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.callInternal(ApiProxyLocalImpl.java:435)
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.call(ApiProxyLocalImpl.java:412)
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.call(ApiProxyLocalImpl.java:391)
	at java.util.concurrent.Executors$PrivilegedCallable$1.run(Executors.java:493)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.concurrent.Executors$PrivilegedCallable.call(Executors.java:490)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- retrieveMessages -->
  <testcase name="saveMessage" time="0.000" classname="BackEndTesting.MessageEntityTest"/>
  <testcase name="saveMessage" time="0.004" classname="BackEndTesting.MessageEntityTest"/>
  <testcase name="retrieveMessages" time="0.003" classname="BackEndTesting.MessageEntityTest">
    <failure type="com.google.apphosting.api.ApiProxy$CallNotFoundException" message="The API package &#039;datastore_v3&#039; or call &#039;RunQuery()&#039; was not found.">
      <![CDATA[com.google.apphosting.api.ApiProxy$CallNotFoundException: The API package 'datastore_v3' or call 'RunQuery()' was not found.
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.callInternal(ApiProxyLocalImpl.java:435)
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.call(ApiProxyLocalImpl.java:412)
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.call(ApiProxyLocalImpl.java:391)
	at java.util.concurrent.Executors$PrivilegedCallable$1.run(Executors.java:493)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.concurrent.Executors$PrivilegedCallable.call(Executors.java:490)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- retrieveMessages -->
  <testcase name="retrieveMessages" time="0.729" classname="BackEndTesting.MessageEntityTest">
    <failure type="com.google.apphosting.api.ApiProxy$CallNotFoundException" message="The API package &#039;datastore_v3&#039; or call &#039;RunQuery()&#039; was not found.">
      <![CDATA[com.google.apphosting.api.ApiProxy$CallNotFoundException: The API package 'datastore_v3' or call 'RunQuery()' was not found.
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.callInternal(ApiProxyLocalImpl.java:435)
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.call(ApiProxyLocalImpl.java:412)
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.call(ApiProxyLocalImpl.java:391)
	at java.util.concurrent.Executors$PrivilegedCallable$1.run(Executors.java:493)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.concurrent.Executors$PrivilegedCallable.call(Executors.java:490)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- retrieveMessages -->
  <testcase name="saveMessage" time="0.001" classname="BackEndTesting.MessageEntityTest"/>
  <testcase name="retrieveMessages" time="0.004" classname="BackEndTesting.MessageEntityTest">
    <failure type="com.google.apphosting.api.ApiProxy$CallNotFoundException" message="The API package &#039;datastore_v3&#039; or call &#039;RunQuery()&#039; was not found.">
      <![CDATA[com.google.apphosting.api.ApiProxy$CallNotFoundException: The API package 'datastore_v3' or call 'RunQuery()' was not found.
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.callInternal(ApiProxyLocalImpl.java:435)
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.call(ApiProxyLocalImpl.java:412)
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.call(ApiProxyLocalImpl.java:391)
	at java.util.concurrent.Executors$PrivilegedCallable$1.run(Executors.java:493)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.concurrent.Executors$PrivilegedCallable.call(Executors.java:490)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- retrieveMessages -->
  <testcase name="retrieveMessages" time="0.002" classname="BackEndTesting.MessageEntityTest">
    <failure type="com.google.apphosting.api.ApiProxy$CallNotFoundException" message="The API package &#039;datastore_v3&#039; or call &#039;RunQuery()&#039; was not found.">
      <![CDATA[com.google.apphosting.api.ApiProxy$CallNotFoundException: The API package 'datastore_v3' or call 'RunQuery()' was not found.
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.callInternal(ApiProxyLocalImpl.java:435)
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.call(ApiProxyLocalImpl.java:412)
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.call(ApiProxyLocalImpl.java:391)
	at java.util.concurrent.Executors$PrivilegedCallable$1.run(Executors.java:493)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.concurrent.Executors$PrivilegedCallable.call(Executors.java:490)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- retrieveMessages -->
  <testcase name="saveMessage" time="0.025" classname="BackEndTesting.MessageEntityTest">
    <failure type="com.google.apphosting.api.ApiProxy$CallNotFoundException" message="The API package &#039;datastore_v3&#039; or call &#039;RunQuery()&#039; was not found.">
      <![CDATA[com.google.apphosting.api.ApiProxy$CallNotFoundException: The API package 'datastore_v3' or call 'RunQuery()' was not found.
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.callInternal(ApiProxyLocalImpl.java:435)
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.call(ApiProxyLocalImpl.java:412)
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.call(ApiProxyLocalImpl.java:391)
	at java.util.concurrent.Executors$PrivilegedCallable$1.run(Executors.java:493)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.concurrent.Executors$PrivilegedCallable.call(Executors.java:490)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- saveMessage -->
  <testcase name="retrieveMessages" time="0.003" classname="BackEndTesting.MessageEntityTest">
    <failure type="com.google.apphosting.api.ApiProxy$CallNotFoundException" message="The API package &#039;datastore_v3&#039; or call &#039;RunQuery()&#039; was not found.">
      <![CDATA[com.google.apphosting.api.ApiProxy$CallNotFoundException: The API package 'datastore_v3' or call 'RunQuery()' was not found.
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.callInternal(ApiProxyLocalImpl.java:435)
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.call(ApiProxyLocalImpl.java:412)
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.call(ApiProxyLocalImpl.java:391)
	at java.util.concurrent.Executors$PrivilegedCallable$1.run(Executors.java:493)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.concurrent.Executors$PrivilegedCallable.call(Executors.java:490)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- retrieveMessages -->
  <testcase name="retrieveMessages" time="0.003" classname="BackEndTesting.MessageEntityTest">
    <failure type="com.google.apphosting.api.ApiProxy$CallNotFoundException" message="The API package &#039;datastore_v3&#039; or call &#039;RunQuery()&#039; was not found.">
      <![CDATA[com.google.apphosting.api.ApiProxy$CallNotFoundException: The API package 'datastore_v3' or call 'RunQuery()' was not found.
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.callInternal(ApiProxyLocalImpl.java:435)
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.call(ApiProxyLocalImpl.java:412)
	at com.google.appengine.tools.development.ApiProxyLocalImpl$AsyncApiCall.call(ApiProxyLocalImpl.java:391)
	at java.util.concurrent.Executors$PrivilegedCallable$1.run(Executors.java:493)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.concurrent.Executors$PrivilegedCallable.call(Executors.java:490)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- retrieveMessages -->
</testsuite> <!-- BackEndTesting.MessageEntityTest -->
